"""Voicebox as VoiceProvider — local voice cloning and TTS."""

import logging
from pathlib import Path
from typing import Optional

from .providers import VoiceProvider
from .voicebox_client import VoiceboxClient

logger = logging.getLogger("ScriptToScreen")


class VoiceboxVoiceProvider(VoiceProvider):
    """Local voice cloning and TTS via Voicebox REST API."""

    def __init__(
        self,
        server_url: str = "http://127.0.0.1:17493",
        engine: str = "qwen",
        model_size: str = "1.7B",
        **kwargs,
    ):
        self._client = VoiceboxClient(server_url)
        self.engine = engine
        self.model_size = model_size

    def test_connection(self) -> bool:
        return self._client.test_connection()

    def test_connection_details(self) -> tuple[bool, str]:
        return self._client.test_connection_details()

    def clone_voice(self, name: str, audio_paths: list[str], **kwargs) -> str:
        """
        Clone a voice from audio samples via Voicebox.

        Finds or creates a profile, uploads each audio sample, and returns
        the profile_id (which acts as the voice_id for generation).
        If a profile with the same name already exists, reuses it.
        Reference text is auto-generated from the filename if not provided.
        """
        language = kwargs.get("language", "en")

        # Check if a profile with this name already exists
        profile_id = None
        existing_sample_count = 0
        try:
            existing = self._client.list_profiles()
            for p in existing:
                if p.get("name", "").lower() == name.lower():
                    profile_id = p.get("id", "")
                    existing_sample_count = p.get("sample_count", 0)
                    logger.info(
                        f"Voicebox profile already exists: {name} -> {profile_id} "
                        f"({existing_sample_count} samples)"
                    )
                    break
        except Exception as e:
            logger.warning(f"Could not list profiles: {e}")

        # Create new profile only if one doesn't exist
        if not profile_id:
            profile = self._client.create_profile(name=name, language=language)
            profile_id = profile.get("id", "")
            logger.info(f"Voicebox profile created: {name} -> {profile_id}")

        # Upload each audio sample (reference_text auto-generated by client if empty)
        uploaded = 0
        skipped = 0
        for path in audio_paths:
            ref_text = kwargs.get("reference_text", "")
            try:
                self._client.add_sample(
                    profile_id=profile_id,
                    audio_path=path,
                    reference_text=ref_text,
                )
                uploaded += 1
                logger.info(f"  Sample uploaded: {Path(path).name}")
            except ValueError as ve:
                # Duration too short or other validation error
                logger.warning(f"  Skipped sample: {ve}")
                skipped += 1
            except Exception as e:
                logger.error(f"  Sample upload failed for {Path(path).name}: {e}")
                skipped += 1

        total_samples = existing_sample_count + uploaded
        if total_samples == 0:
            raise RuntimeError(
                f"No valid samples for '{name}'. "
                f"Ensure audio files are at least 2.0 seconds long."
            )

        logger.info(
            f"Voice profile '{name}': {uploaded} new samples uploaded, "
            f"{skipped} skipped, {total_samples} total"
        )
        return profile_id

    def generate_speech(
        self,
        voice_id: str,
        text: str,
        save_path: str,
        **kwargs,
    ) -> str:
        """
        Generate speech using a Voicebox voice profile.

        Uses the streaming endpoint for synchronous file output,
        which is simpler and doesn't require polling.
        Auto-loads the TTS model if not already loaded.
        Returns the actual path where audio was saved (.wav).
        """
        engine = kwargs.get("engine", self.engine)
        model_size = kwargs.get("model_size", self.model_size)
        language = kwargs.get("language", "en")

        # Ensure the TTS model is loaded before generating
        self._client.ensure_model_loaded(engine, model_size)

        # Ensure the file extension is .wav (Voicebox outputs WAV)
        save_path_wav = save_path
        if not save_path.lower().endswith(".wav"):
            save_path_wav = str(Path(save_path).with_suffix(".wav"))

        # Use the STREAMING endpoint — synchronous, returns WAV data
        # directly.  The async generate+poll path has a race condition
        # where Voicebox marks status=completed but never populates
        # audio_path, causing the poll to loop forever.
        logger.info(f"Voicebox generating speech (streaming): {text[:60]}...")
        self._client.generate_speech_stream(
            profile_id=voice_id,
            text=text,
            save_path=save_path_wav,
            language=language,
            engine=engine,
            model_size=model_size,
        )

        actual_dur = self._client.get_wav_duration(save_path_wav)
        if actual_dur < 0.1:
            raise RuntimeError(
                f"Generated audio is empty or too short ({actual_dur:.3f}s). "
                f"Voicebox may need more time to initialize."
            )

        logger.info(
            f"Voicebox speech generated: {save_path_wav} ({actual_dur:.1f}s)"
        )
        return save_path_wav

    def list_voices(self) -> list[dict]:
        """List Voicebox voice profiles."""
        try:
            profiles = self._client.list_profiles()
            # Normalize to a common format
            voices = []
            for p in profiles:
                voices.append({
                    "voice_id": p.get("id", ""),
                    "name": p.get("name", "Unknown"),
                    "language": p.get("language", "en"),
                    "provider": "voicebox",
                })
            return voices
        except Exception as e:
            logger.error(f"Failed to list Voicebox profiles: {e}")
            return []
